[package]
name = "wasm"
version = "0.1.0"
authors = ["Exr0n <spotyie@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/Exr0n/learn_wasm_rust"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

